### ISSUE TITLE
[bug] solid colour thumbnails are created

### ISSUE THREAD

**Issue by rnusser** [k-ivan/visual-bookmarks-chrome#106] opened 2022-12-17 12:23 UTC
I tried right clicking on a bookmark and then `Refresh thumbnail`. I however usually get a solid blue, white or black thumbnail. I can see the extension launches the bookmarked page and I can see what looks like the correct screenshot vanishing into the mac dock, and then the thumbnail becomes one of those solid colours.

Do you have any ideas what it could be, as this extension is otherwise lovely?

**Comment by k-ivan** [comment] 2022-12-17 18:29
This is strange, try increasing the delay in settings before saving a screenshot
![image](https://user-images.githubusercontent.com/6150895/208256251-e8c4f23f-4747-4594-ad9c-ed00efc113af.png)

**Comment by rnusser** [comment] 2022-12-20 09:14
Thanks for the response. I have moved it all the way up to 15 seconds, but I still have the same result:

<img width="585" alt="Screenshot 2022-12-20 at 10 23 42" src="https://user-images.githubusercontent.com/7140189/208629068-b4476c1d-ec14-4cb7-8c8f-f3a4288d0e9c.png">

**Comment by k-ivan** [comment] 2022-12-21 07:26
Perhaps the site is blocked by your ISP? I tried with the BBC site, a screenshot was created.

Before trying to take a screenshot, please open the devtools(F12) and the console tab and take a screenshot of the message that will be there.
![image](https://user-images.githubusercontent.com/6150895/208845359-19c3913c-f11c-499c-9d5c-bb9988bdaa4a.png)

**Comment by k-ivan** [comment] 2023-01-07 18:03
Since I did not receive an answer from you and the problem seems to be local, I will close this issue.

If the issue is not resolved and you have more information, please reopen this issue.

**Closed by k-ivan** 2023-01-07 18:03 UTC
